[package]
name = "interactcli-rs"
version = "0.1.0"
authors = ["jiashiwen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
rustyline = "9.0.0"
shellwords = "1.1.0"
log = "0.4"
log4rs = "1.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
cfg-if = "1.0"
memchr = "2.0"
rustyline-derive = "0.5.0"
lazy_static = "1.4.0"
config = "0.11.0"
yaml-rust = "0.4.5"

reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
url = "2.2.2"
prettytable-rs = "^0.8"


[[example]]
name = "readline"
path = "examples/readlinesample.rs"

[[example]]
name = "autocomplete"
path = "examples/autocomplete.rs"

[[example]]
name = "configrs"
path = "examples/configrs.rs"

[[example]]
name = "yamlparser"
path = "examples/yamlparser.rs"